<?php
return array(
    'conditions' => array(
        "english" => array(
            " Whirlwind ",
            " Tropical Storm ",
            " The Tempest",
            " Severe storms ",
            " Lightning ",
            " Rain and snow together",
            " Rain and Hail ",
            " snow and rain",
            " Freezing drizzle ",
            " Drizzle ",
            " Cold Rain ",
            " Rain ",
            " Rain ",
            " Snow ",
            " Rain and Snow ",
            " Snow with wind ",
            " Snow ",
            " Hail ",
            " Frost ",
            " Dust",
            " Foggy ",
            " Fog and Mist ",
            " Smoked ",
            " Wind ",
            " Wind ",
            " Cold",
            " Cloudy ",
            " Night Rain ",
            " Mostly Cloudy ",
            " Night Partly Cloudy ",
            " Clear Day ",
            " Night Clear ",
            " Sunny ",
            " Moonlit night ",
            " Day ",
            " Rain and hail together",
            " Very hot",
            " Lightning ",
            " Rain ",
            " Rain ",
            " Rain ",
            " Heavy snow ",
            " Snow courses ",
            " Heavy snow ",
            " Rain ",
            " Drizzle ",
            " Rain and Snow ",
            " Lightning ",
            3200 => " Not available "
            ) ,
    'arabic' => array(
        "الزوبعة",
        "العاصفة الاستوائية",
        "العاصفة",
        "العواصف الشديدة",
        "البرق",
        "المطر والثلج معا",
        "المطر والبرد",
        "الثلج والثلوج والأمطار",
        "تجميد رذاذ",
        "رذاذ",
        "المطر الباردة",
        "المطر",
        "المطر",
        "الثلج",
        "الأمطار والثلوج",
        "الثلج مع الريح",
        "الثلج",
        "حائل",
        "فروست",
        "الغبار",
        "ضبابية",
        "الضباب والضباب",
        "المدخن",
        "الرياح",
        "الرياح",
        "الباردة",
        "غائم",
        "ليلة المطر",
        "ضباب",
        "ليلة غائم جزئيا",
        "مسح اليوم",
        "ليلة واضحة",
        "صني",
        "ليلة مقمرة",
        "اليوم",
        "المطر والبرد معا",
        "حار جداً",
        "البرق",
        "المطر",
        "المطر",
        "المطر",
        "الثلوج",
        "دورات الثلوج",
        "الثلوج",
        "المطر",
        "رذاذ",
        "الأمطار والثلوج",
        "البرق",
        3200 => "غير متوفر"
        ) ,
    'bulgarian' => array(
        "Вихрушка",
        "Тропическа буря",
        "Tempest",
        "Тежки бури",
        "Светкавица",
        "Дъжд и сняг заедно",
        "Дъжд и градушка",
        "Сняг, сняг и дъжд",
        "Замразяването ръми",
        "Ръми",
        "Студен дъжд",
        "Дъжд",
        "Дъжд",
        "Сняг",
        "Дъжд и сняг",
        "Сняг с вятъра",
        "Сняг",
        "Градушка",
        "Мраз",
        "Прах",
        "Мъгла",
        "Мъгла и мъгла",
        "Пушени",
        "Вятър",
        "Вятър",
        "Студена",
        "Мътен",
        "Нощ дъжд",
        "Дъжд",
        "Нощ дъжд",
        "Ясен ден",
        "Нощта е ясно",
        "Слънчево",
        "Лунна нощ",
        "Ден",
        "Дъжд и градушка заедно",
        "Много горещо",
        "Светкавица",
        "Дъжд",
        "Дъжд",
        "Дъжд",
        "Тежък сняг",
        "Сняг курсове",
        "Тежък сняг",
        "Дъжд",
        "Ръми",
        "Дъжд и сняг",
        "Светкавица",
        3200 => "не е наличен"
        ) ,
    'catalan' => array(
        "Remolí",
        "Tempesta Tropical",
        "La tempesta",
        "Tempestes",
        "Llamp",
        "Pluja i neu junts",
        "Pluja i calamarsa",
        "Neu, neu i pluja",
        "Congelació plugim",
        "Plugim",
        "Pluja freda",
        "Pluja",
        "Pluja",
        "Neu",
        "Pluja i neu",
        "Neu amb vent",
        "Neu",
        "Déu vos salve",
        "Frost",
        "Pols",
        "Boira",
        "Boira i boirina",
        "Fumat",
        "Vent",
        "Vent",
        "Fred",
        "Núvols",
        "Pluja de nit",
        "Plugim",
        "Nit de boira",
        "Dia de neteja",
        "Nit clara",
        "Sol",
        "Nit de Lluna",
        "Dia",
        "Pluja i calamarsa junts",
        "Molt calent",
        "Llamp",
        "Pluja",
        "Pluja",
        "Pluja",
        "Boirina",
        "Camps de neu",
        "Boirina",
        "Pluja",
        "Plugim",
        "Pluja i neu",
        "Llamp",
        3200 => "no disponible"
        ) ,
    'chinese-simplified' => array(
        "旋风",
        "热带风暴",
        "暴风雨",
        "严重风暴",
        "闪电",
        "雨和雪在一起",
        "雨和冰雹",
        "雪、 雪和雨",
        "冻毛毛雨",
        "毛毛雨",
        "冷雨",
        "雨",
        "雨",
        "雪",
        "雨和雪",
        "雪与风",
        "雪",
        "冰雹",
        "霜",
        "尘",
        "大雾",
        "雾和雾",
        "熏",
        "风",
        "风",
        "冷",
        "多云",
        "晚上雨",
        "多云",
        "晚晴转多云",
        "清除一天",
        "夜清除",
        "阳光明媚",
        "月夜",
        "天",
        "雨和冰雹在一起",
        "很热",
        "闪电",
        "雨",
        "雨",
        "雨",
        "大雪",
        "雪课",
        "大雪",
        "雨",
        "毛毛雨",
        "雨和雪",
        "闪电",
        3200 => "不可用"
        ) ,
    'chinese-traditional' => array(
        "旋風",
        "熱帶風暴",
        "暴風雨",
        "嚴重風暴",
        "閃電",
        "雨和雪在一起",
        "雨和冰雹",
        "雪、 雪和雨",
        "凍毛毛雨",
        "毛毛雨",
        "冷雨",
        "雨",
        "雨",
        "雪",
        "雨和雪",
        "雪與風",
        "雪",
        "冰雹",
        "霜",
        "塵",
        "大霧",
        "霧和霧",
        "熏",
        "風",
        "風",
        "冷",
        "多雲",
        "晚上雨",
        "多雲",
        "晚晴轉多雲",
        "清除一天",
        "夜清除",
        "陽光明媚",
        "月夜",
        "天",
        "雨和冰雹在一起",
        "很熱",
        "閃電",
        "雨",
        "雨",
        "雨",
        "大雪",
        "雪課",
        "大雪",
        "雨",
        "毛毛雨",
        "雨和雪",
        "閃電",
        3200 => "不可用"
        ),
    'danish' => array(
        "Hvirvelvind",
        "Tropisk Storm",
        "Tempest",
        "Voldsomme storme",
        "Lyn",
        "Regn og sne sammen",
        "Regn og hagl",
        "Sne, sne og regn",
        "Fastfrysning støvregn",
        "Støvregn",
        "Kolde regn",
        "Regn",
        "Regn",
        "Sne",
        "Regn og sne",
        "Sne med vinden",
        "Sne",
        "Hail",
        "Frost",
        "Støv",
        "Tåget",
        "Tåge og dis",
        "Røget",
        "Wind",
        "Wind",
        "Kold",
        "Skyet",
        "Natten regn",
        "Skyet",
        "Aften tordenvejr",
        "Ryd dag",
        "Nat klar",
        "Sunny",
        "Moonlit night",
        "Dagen",
        "Regn og hagl sammen",
        "Meget varm",
        "Lyn",
        "Regn",
        "Regn",
        "Regn",
        "Tunge sne",
        "Sne kurser",
        "Tunge sne",
        "Regn",
        "Støvregn",
        "Regn og sne",
        "Lyn",
        3200 => "ikke tilgængelig"
        ),
    'dutch' => array(
        "Wervelwind",
        "Tropische Storm",
        "The Tempest",
        "Zware stormen",
        "Bliksem",
        "Regen en sneeuw samen",
        "Regen en hagel",
        "Snow, sneeuw en regen",
        "Bevriezing motregen",
        "Motregen",
        "Koude Rain",
        "Rain",
        "Rain",
        "Snow",
        "Regen en sneeuw",
        "Sneeuw met wind",
        "Snow",
        "Hail",
        "Frost",
        "Dust",
        "Mistig",
        "Mist en nevel",
        "Gerookt",
        "Wind",
        "Wind",
        "Koud",
        "Bewolkt",
        "Nacht Rain",
        "Overwegend bewolkt",
        "Night gedeeltelijk bewolkt",
        "Clear dag",
        "Nacht Clear",
        "Sunny",
        "Moonlit night",
        "Day",
        "Regen en hagel samen",
        "Erg heet",
        "Bliksem",
        "Rain",
        "Rain",
        "Rain",
        "Zware sneeuwval",
        "Snow cursussen",
        "Zware sneeuwval",
        "Rain",
        "Motregen",
        "Regen en sneeuw",
        "Bliksem",
        3200 => "niet beschikbaar"
        ),
    'estonian' => array(
        "Keeristorm",
        "Troopiline torm",
        "Tempest",
        "Rajudele",
        "Välk",
        "Vihm ja lumi kokku.",
        "Vihma ja rahe",
        "Lumi, lumi ja vihm",
        "Jäine vihm",
        "Tibutama",
        "Külm vihm",
        "Vihm",
        "Vihm",
        "Lumi",
        "Vihm ja lumi.",
        "Lumi Tuul",
        "Lumi",
        "Rahe",
        "Külma",
        "Tolmu",
        "Udune",
        "Udu ja udu",
        "Suitsutatud",
        "Tuul",
        "Tuul",
        "Külm",
        "Pilves",
        "Öö vihma",
        "Udu",
        "Öine udu",
        "Selge päev",
        "Öö selge",
        "Sunny",
        "Kuuvalge öö",
        "Päev",
        "Vihma ja rahe üheskoos.",
        "Väga Kuumad",
        "Välk",
        "Vihm",
        "Vihm",
        "Vihm",
        "Tugev lumesadu",
        "Lumi kursused",
        "Tugev lumesadu",
        "Vihm",
        "Tibutama",
        "Vihm ja lumi.",
        "Välk",
        3200 => "pole saadaval"
        ) ,
    'finnish' => array(
        "Tuulenpyörre",
        "Trooppinen myrsky",
        "Tempest",
        "Ankarien myrskyjen",
        "Salama",
        "Sade ja lumi yhdessä",
        "Sadetta ja rakeita",
        "Lunta, lunta ja sadetta",
        "Jäädyttäminen tihkusade",
        "Tihkusadetta",
        "Kylmä sade",
        "Rain",
        "Rain",
        "Lunta",
        "Sade ja lumi",
        "Lunta ja tuuli",
        "Lunta",
        "Terve",
        "Frost",
        "Pöly",
        "Sumuinen",
        "Sumu ja sumun",
        "Polttaa",
        "Wind",
        "Wind",
        "Kylmä",
        "Samea",
        "Yö Rain",
        "Selkeää",
        "Night pilvistä",
        "Selvä päivä",
        "Yö Tyhjennä",
        "Sunny",
        "Kuutamoyönä",
        "Day",
        "Sadetta ja rakeita yhdessä",
        "Erittäin kuuma",
        "Salama",
        "Rain",
        "Rain",
        "Rain",
        "Lumisadetta",
        "Lumi kurssit",
        "Lumisadetta",
        "Rain",
        "Tihkusadetta",
        "Sade ja lumi",
        "Salama",
        3200 => "ei käytettävissä"
        ),
    'french' => array(
        " Tourbillon ",
        " Tempête tropicale ",
        " La tempête ",
        " Orages ",
        " La foudre ",
        " La pluie et neige ensemble ",
        " La pluie et la grêle ",
        " Neige, neige et pluie ",
        " Bruine verglaçante ",
        " Arroser ",
        " Cold Rain ",
        " Rain ",
        " Rain ",
        " Neige ",
        " Rain and Snow ",
        " La neige avec le vent ",
        " Neige ",
        " Salut ",
        " Gel ",
        " Dust ",
        " Brumeux ",
        " Brouillard et la brume ",
        " Fumé ",
        " Vent ",
        " Vent ",
        " Froid ",
        " Nuageux ",
        " Pluie de la nuit ",
        " Nuageux ",
        " Nuit sans nuages ",
        " Clair de jour ",
        " Clair de nuit ",
        " Sunny ",
        " Nuit de pleine lune ",
        " Jour ",
        " La pluie et grêle ensemble ",
        " Très chaud ",
        " La foudre ",
        " Rain ",
        " Rain ",
        " Rain ",
        " Neige ",
        " Cours de neige ",
        " Neige ",
        " Rain ",
        " Arroser ",
        " Rain and Snow ",
        " La foudre ",
        3200 => "non disponible"
        ),
    'german' => array(
        "Wirbelwind",
        "Tropischer Sturm",
        "The Tempest",
        "Unwetter",
        "Blitz",
        "Regen und Schnee zusammen",
        "Regen und Hagel",
        "Schnee, Schnee und Regen",
        "Einfrieren Nieselregen",
        "Drizzle",
        "Cold Rain",
        "Rain",
        "Rain",
        "Schnee",
        "Rain and Snow",
        "Schnee mit Wind",
        "Schnee",
        "Hail",
        "Frost",
        "Dust",
        "Nebelig",
        "Nebel und Nebel",
        "Geraucht",
        "Wind",
        "Wind",
        "Kalt",
        "Bewölkt",
        "Nacht-Rain",
        "Meist bewölkt",
        "Nacht bedeckt",
        "Klare Tag",
        "Nacht klar",
        "Sonnig",
        "Moonlit Night",
        "Day",
        "Regen und Hagel zusammen",
        "Sehr heiß",
        "Blitz",
        "Rain",
        "Rain",
        "Rain",
        "Schweren Schnee",
        "Schnee-Kurse",
        "Schweren Schnee",
        "Rain",
        "Drizzle",
        "Rain and Snow",
        "Blitz",
        3200 => "nicht verfügbar"
        ) ,
    'greek' => array(
        "Whirlwind",
        "Τροπική καταιγίδα",
        "Η Τρικυμία",
        "Αυστηρές θύελλες",
        "Αστραπή",
        "Βροχή και χιόνι μαζί",
        "Βροχή και το χαλάζι",
        "Χιόνι, χιόνι και βροχή",
        "Δέσμευση ψιλόβροχο",
        "Ψιχαλίζει",
        "Κρύο βροχή",
        "Βροχή",
        "Βροχή",
        "Χιόνι",
        "Βροχή και χιόνι",
        "Χιόνι με άνεμο",
        "Χιόνι",
        "Χαλάζι",
        "Frost",
        "Σκόνη",
        "Ομιχλώδη",
        "Ομίχλη και την ομίχλη",
        "Καπνιστό",
        "Άνεμος",
        "Άνεμος",
        "Κρύο",
        "Θολό",
        "Βροχή το βράδυ",
        "Συννεφιά",
        "Νύχτα καταιγίδα",
        "Σαφείς ημέρα",
        "Νύχτα Clear",
        "ΣΑΝΙ",
        "Νύχτες με φεγγάρι",
        "Ημέρα",
        "Βροχή και χαλάζι μαζί",
        "Πολύ ζεστό",
        "Αστραπή",
        "Βροχή",
        "Βροχή",
        "Βροχή",
        "Βαρύ χιόνι",
        "Χιόνι μαθήματα",
        "Βαρύ χιόνι",
        "Βροχή",
        "Ψιχαλίζει",
        "Βροχή και χιόνι",
        "Αστραπή",
        3200 => "δεν είναι διαθέσιμη"
        ) ,
    'haitian-creole' => array(
        "Toubiyon",
        "Twopikal Tempête",
        "La tanpèt",
        "Sevè delij",
        "Foudre",
        "Lapli Et neige ansanm",
        "Lapli ak lagrèl",
        "Neige, lanèj ak lapli",
        "Pou bloke brin",
        "Farinen",
        "Lapli fwèt",
        "Lapli",
        "Lapli",
        "Neige",
        "Lapli tonbe, lanèj",
        "Lanèj ak van",
        "Neige",
        "Lagrèl",
        "Frost",
        "Pousyè",
        "Brouya",
        "Bouya Et farinay",
        "Fumé",
        "Van",
        "Van",
        "Frèt",
        "Très",
        "Nuit lapli",
        "Surtout très",
        "Nuit en très",
        "Effacer jou",
        "Jou lannwit sa a Clear",
        "Sunny",
        "Moonlit nuit",
        "Jou",
        "Lapli ak lagrèl ansanm",
        "Anpil cho",
        "Foudre",
        "Lapli",
        "Lapli",
        "Lapli",
        "Lou neige",
        "Neige kou",
        "Lou neige",
        "Lapli",
        "Farinen",
        "Lapli tonbe, lanèj",
        "Foudre",
        3200 => "pa disponib"
        ) ,
    'hindi' => array(
        "बवंडर",
        "उष्णकटिबंधीय तूफान",
        'टेम्पेस्ट',
        "गंभीर तूफान",
        "बिजली",
        "वर्षा और बर्फ की एक साथ",
        "बारिश और ओलों",
        "बर्फ, बर्फ और बारिश",
        "बर्फ़ीली बूंदा बांदी",
        "बूंदा बांदी",
        "ठंडी बारिश",
        "वर्षा",
        "वर्षा",
        "बर्फ",
        "वर्षा और हिमपात",
        "पवन के साथ बर्फ",
        "बर्फ",
        "जय हो",
        "फ्रॉस्ट",
        "धूल",
        "धूमिल",
        "कोहरे और धुंध",
        "धूम्रपान",
        "पवन",
        "पवन",
        "ठंड",
        "बादल",
        "रात बारिश",
        "अधिकतर बदली",
        "आंशिक रूप से बादल छाए रहेंगे रात",
        "दिन साफ़ करें",
        "रात साफ",
        "सनी",
        'चांदनी रात',
        "दिन",
        "बारिश और ओलों एक साथ",
        "बहुत ही हॉट",
        "बिजली",
        "वर्षा",
        "वर्षा",
        "वर्षा",
        "भारी हिमपात",
        "बर्फ पाठ्यक्रम",
        "भारी हिमपात",
        "वर्षा",
        "बूंदा बांदी",
        "वर्षा और हिमपात",
        "बिजली",
        3200 => "उपलब्ध नहीं है"
        ) ,
    'indonesian' => array(
        "Angin puyuh",
        "Tropical Storm",
        "The Tempest",
        "Badai berat",
        "Lightning",
        "Hujan dan salju bersama-sama",
        "Hujan dan hujan es",
        "Salju, salju dan hujan",
        "Merata",
        "Gerimis",
        "Dingin hujan",
        "Hujan",
        "Hujan",
        "Salju",
        "Hujan dan salju",
        "Salju dengan angin",
        "Salju",
        "Hail",
        "Es",
        "Debu",
        "Berkabut",
        "Kabut dan kabut",
        "Merokok",
        "Angin",
        "Angin",
        "Dingin",
        "Berawan",
        "Malam hujan",
        "Kabut",
        "Malam hujan",
        "Jelas hari",
        "Clear malam",
        "Sunny",
        "Malam bulan purnama",
        "Hari",
        "Hujan dan hujan es bersama-sama",
        "Sangat panas",
        "Lightning",
        "Hujan",
        "Hujan",
        "Hujan",
        "Berat salju",
        "Snow kursus",
        "Berat salju",
        "Hujan",
        "Gerimis",
        "Hujan dan salju",
        "Lightning",
        3200 => "tidak tersedia"
        ) ,
    'italian' => array(
        "Whirlwind",
        "Tempesta tropicale",
        "La tempesta",
        "Tempeste",
        "Fulmine",
        "Pioggia e neve insieme",
        "Pioggia e grandine",
        "Neve, neve e pioggia",
        "Congelamento pioggerella",
        "Pioggerella",
        "Pioggia fredda",
        "Pioggia",
        "Pioggia",
        "Neve",
        "Pioggia e la neve",
        "La neve con il vento",
        "Neve",
        "Grandine",
        "Gelo",
        "Polvere",
        "Nebbia",
        "Nebbia e foschia",
        "Affumicato",
        "Vento",
        "Vento",
        "Freddo",
        "Nuvoloso",
        "Pioggia di notte",
        "Nuvoloso",
        "Night parzialmente nuvoloso",
        "Chiaro giorno",
        "Notte chiara",
        "Sunny",
        "Notte di luna",
        "Giorno",
        "Pioggia e grandine insieme",
        "Molto caldo",
        "Fulmine",
        "Pioggia",
        "Pioggia",
        "Pioggia",
        "Neve",
        "Corsi di neve",
        "Neve",
        "Pioggia",
        "Pioggerella",
        "Pioggia e la neve",
        "Fulmine",
        3200 => "non disponibile"
        ) ,
    'japanese' => array(
        "旋風",
        "熱帯ストーム",
        "テンペスト",
        "激しい嵐",
        "ライトニング",
        "雨と雪の一緒に",
        "雨と雹",
        "雪、雪や雨",
        "凍結の霧雨",
        "しぐれ",
        "冷たい雨",
        "雨",
        "雨",
        "雪",
        "雨と雪",
        "雪風",
        "雪",
        "あられ",
        "霜",
        "塵",
        "霧深い",
        "霧と霧",
        "スモーク",
        "風",
        "風",
        "冷たい",
        "曇り",
        "夜雨",
        "曇り",
        "曇りの夜",
        "クリア日",
        "夜のクリア",
        "晴れ",
        "月明かりに照らされた夜",
        "日",
        "雨と雹一緒に",
        "非常に熱い",
        "ライトニング",
        "雨",
        "雨",
        "雨",
        "大雪",
        "雪コース",
        "大雪",
        "雨",
        "しぐれ",
        "雨と雪",
        "ライトニング",
        3200 => "利用できません"
        ) ,
    'korean' => array(
        "소용돌이",
        "열 대 폭풍",
        "폭풍우",
        "폭풍우",
        "번개",
        "비와 눈이 함께",
        "비와 우박",
        "눈, 눈, 비",
        "이슬비 동결",
        "이슬비",
        "찬 비",
        "비",
        "비",
        "눈",
        "비와 눈",
        "바람과 함께 눈",
        "눈",
        "만 세",
        "서 리",
        "먼지",
        "안개",
        "안개와 안개",
        "훈제",
        "바람",
        "바람",
        "감기",
        "흐린",
        "밤 비",
        "대체로 흐림",
        "밤 밤",
        "맑은 날",
        "명확한 밤",
        "써니",
        "달 밤",
        "하루",
        "비와 함께 우박",
        "아주 뜨거운",
        "번개",
        "비",
        "비",
        "비",
        "폭설",
        "눈 코스",
        "폭설",
        "비",
        "이슬비",
        "비와 눈",
        "번개",
        3200 => "사용할 수 없음"
        ) ,
    'latvian' => array(
        "Viesulis",
        "Tropical Storm",
        "Vētras",
        "Spēcīgas vētras",
        "Zibens",
        "Lietus un sniega kopā",
        "Lietus un krusa",
        "Sniegu, sniega un lietus",
        "Līdzekļu iesaldēšana līņāt",
        "Lietus",
        "Aukstās lietus",
        "Lietus",
        "Lietus",
        "Snow",
        "Lietus un sniega",
        "Sniega ar vēju",
        "Snow",
        "Krusa",
        "Salnas",
        "Putekļi",
        "Migla",
        "Migla un dūmaka",
        "Kūpinātu",
        "Vējš",
        "Vējš",
        "Aukstā",
        "Fair",
        "Vakarā lietū",
        "Snow",
        "Clear night",
        "Skaidra diena",
        "Nakts skaidrs",
        "Sunny",
        "Mēness apspīdēts naktī",
        "Diena",
        "Lietus un krusa kopā",
        "Ļoti karsti",
        "Zibens",
        "Lietus",
        "Lietus",
        "Lietus",
        "Smagā sniega",
        "Sniega kursi",
        "Smagā sniega",
        "Lietus",
        "Lietus",
        "Lietus un sniega",
        "Zibens",
        3200 => "nav pieejams"
        ) ,
    'maltese' => array(
        "Lembut",
        "Tropikali tax-xita",
        "-Tempest",
        "Maltempijiet severi",
        "Sajjetti",
        "Ix-xita u borra flimkien",
        "Ix-xita u mis-silġ",
        "Tas-silġ, borra u x-xita",
        "Iffriżar drizzle",
        "Drizzle",
        "Xita kiesaħ",
        "Xita",
        "Xita",
        "Snow",
        "Ix-xita u borra",
        "L-borra b ' riħ",
        "Snow",
        "Sejħa",
        "Ġlata",
        "Trab",
        "Foggy",
        "Ċpar u ċpar",
        "Affumikat",
        "Riħ",
        "Riħ",
        "Kiesaħ",
        "Imdardar",
        "Ix-xita bil-lejl",
        "Aktar imdardar",
        "Lejl parzjalment imdardar",
        "Ġurnata ċara",
        "Lejl ċar",
        "Sunny",
        "Moonlit bil-lejl",
        "Jum",
        "Ix-xita u inkwadrat flimkien",
        "Ħafna sħun",
        "Sajjetti",
        "Xita",
        "Xita",
        "Xita",
        "Tqila tas-silġ",
        "Korsijiet tas-silġ",
        "Tqila tas-silġ",
        "Xita",
        "Drizzle",
        "Ix-xita u borra",
        "Sajjetti",
        3200 => "mhux disponibbli"
        ) ,
    'romanian' => array(
        "Vârtej de vânt",
        "Furtuni tropicale",
        "Furtuna",
        "Furtuni severe",
        "Lightning",
        "Ploaie şi de zăpadă împreună",
        "Ploaie si grindina",
        "Zăpadă, zăpadă şi ploaie",
        "Înghețarea cerne",
        "Cerne",
        "Ploaie rece",
        "Rain",
        "Rain",
        "Zăpadă",
        "Ploaie şi zăpadă",
        "Ninsoare cu vânt",
        "Zăpadă",
        "Grindina",
        "Frost",
        "Praf",
        "Ceaţă",
        "Ceaţă şi ceaţă",
        "Afumat",
        "Vânt",
        "Vânt",
        "La rece",
        "Tulbure",
        "Ploaie de noapte",
        "Plouă",
        "Noapte de ploaie",
        "Clar zi",
        "Noaptea clară",
        "Soare",
        "Noapte cu lună plină",
        "Ziua",
        "Ploaie si grindina împreună",
        "Foarte fierbinte",
        "Lightning",
        "Rain",
        "Rain",
        "Rain",
        "Zăpadă",
        "Cursuri de zăpadă",
        "Zăpadă",
        "Rain",
        "Cerne",
        "Ploaie şi zăpadă",
        "Lightning",
        3200 => "nu este disponibil"
        ) ,
    'russian' => array(
        "Вихрь",
        "Тропический шторм",
        "Буря",
        "Ураганы",
        "Молния",
        "Дождь и снег вместе",
        "Дождь и град",
        "Снег, снег и дождь",
        "Замораживания дождь",
        "Дождь",
        "Холодный дождь",
        "Дождь",
        "Дождь",
        "Снег",
        "Дождь и снег",
        "Снег с ветром",
        "Снег",
        "Славься",
        "Мороз",
        "Пыль",
        "Туманный",
        "Туман и туман",
        "Копченая",
        "Ветер",
        "Ветер",
        "Холодный",
        "Гроза",
        "Ночной дождь",
        "Дождь",
        "Ночью Пасмурно",
        "Ясный день",
        "Ночь ясно",
        "Солнечный",
        "Лунная ночь",
        "День",
        "Дождь и град вместе",
        "Очень жарко",
        "Молния",
        "Дождь",
        "Дождь",
        "Дождь",
        "Снег",
        "Снег курсы",
        "Снег",
        "Дождь",
        "Дождь",
        "Дождь и снег",
        "Молния",
        3200 => "не доступен"
        ) ,
    'spanish' => array(
        "Torbellino",
        "Tormenta Tropical",
        "La tempestad",
        "Tormentas",
        "Relámpago",
        "La lluvia y la nieve juntos",
        "La lluvia y el granizo",
        "Nieve, nieve y la lluvia",
        "Congelación llovizna",
        "Llovizna",
        "La lluvia fría",
        "Lluvia",
        "Lluvia",
        "Nieve",
        "Lluvia y la nieve",
        "Nieve con viento",
        "Nieve",
        "Salve",
        "Helada",
        "Polvo",
        "Niebla",
        "Niebla y neblina",
        "Ahumadas",
        "Viento",
        "Viento",
        "Frío",
        "Nublado",
        "Lluvia de la noche",
        "Leve",
        "Noche parcialmente nublada",
        "Claro día",
        "La noche clara",
        "Soleado",
        "Noche de luna llena",
        "Día",
        "La lluvia y granizo juntos",
        "Muy caliente",
        "Relámpago",
        "Lluvia",
        "Lluvia",
        "Lluvia",
        "Nevadas",
        "Cursos de nieve",
        "Nevadas",
        "Lluvia",
        "Llovizna",
        "Lluvia y la nieve",
        "Relámpago",
        3200 => "no disponible"
        ) ,
    'swedish' => array(
        "Virvelvind",
        "Tropiska stormen",
        "Stormen",
        "Svåra stormar",
        "Lightning",
        "Regn och snö tillsammans",
        "– Regn och hagel",
        "Snö, snö och regn",
        "Frysning duggregn",
        "Ringla",
        "Kallt regn",
        "Rain",
        "Rain",
        "Snö",
        "– Regn och snö",
        "Snö med vinden",
        "Snö",
        "Hagel",
        "Frost",
        "Stoft",
        "Dimmigt",
        "– Dimma och dimma",
        "Rökt",
        "Vind",
        "Vind",
        "Kall",
        "Grumlig",
        "Natten regn",
        "Mestadels molnigt",
        "Night molnigt",
        "Rensa dag",
        "Natt klara",
        "Soligt",
        "Månljus natt",
        "Dag",
        "Regn och hagel tillsammans",
        "Mycket varmt",
        "Lightning",
        "Rain",
        "Rain",
        "Rain",
        "Tung snö",
        "Snow kurser",
        "Tung snö",
        "Rain",
        "Ringla",
        "– Regn och snö",
        "Lightning",
        3200 => "inte tillgänglig"
        ) ,
    'turkish' => array(
        "Kasırga",
        "Tropik fırtına",
        "Fırtına",
        "Şiddetli fırtınalar",
        "Yıldırım",
        "Yağmur ve kar birlikte",
        "Yağmur ve dolu",
        "Kar, kar ve yağmur",
        "Dondurucu Çiseleme",
        "Yağmur",
        "Soğuk Rain",
        "Yağmur",
        "Yağmur",
        "Kar",
        "Yağmur ve kar",
        "Kar rüzgar ile",
        "Kar",
        "Çok yaşa",
        "Don",
        "Toz",
        "Sisli",
        "Sis ve buğu",
        "Duman",
        "Rüzgar",
        "Rüzgar",
        "Soğuk",
        "Clear",
        "Gece yağmuru",
        "Yağmur",
        "Gece kar taneleri",
        "GünTemizle",
        "Gece net",
        "Güneş",
        "Mehtaplı gece",
        "Gün",
        "Yağmur ve birlikte yaşa",
        "Çok sıcak",
        "Yıldırım",
        "Yağmur",
        "Yağmur",
        "Yağmur",
        "Kar",
        "Kar kursları",
        "Kar",
        "Yağmur",
        "Yağmur",
        "Yağmur ve kar",
        "Yıldırım",
        3200 => "uygun değil"
        ) ,
    'ukrainian' => array(
        "Вихор",
        "Тропічний шторм",
        "Буря",
        "Урагани",
        "Блискавка",
        "Дощ і сніг разом",
        "Піти дощ і град",
        "Сніг, сніг і дощ",
        "Заморожування дощ",
        "Дощ",
        "Холодний дощ",
        "Дощ",
        "Дощ",
        "Сніг",
        "Дощ і сніг",
        "Сніг з вітром",
        "Сніг",
        "Град",
        "Іній",
        "Пил",
        "Туман",
        "Туману і туман",
        "Ковбаси",
        "Вітер",
        "Вітер",
        "Холодно",
        "Дощ",
        "Ніч дощ",
        "Злива",
        "Ніч злива",
        "Ясний день",
        "Ніч відкритий",
        "Сонячний",
        "Місячна ніч",
        "День",
        "Піти дощ і град разом",
        "Дуже гарячими",
        "Блискавка",
        "Дощ",
        "Дощ",
        "Дощ",
        "Сильний снігопад",
        "Сніг курси",
        "Сильний снігопад",
        "Дощ",
        "Дощ",
        "Дощ і сніг",
        "Блискавка",
        3200 => "не доступний"
        ) ,
    'vietnamese' => array(
        "Cơn lốc",
        "Cơn bão nhiệt đới",
        "Tempest",
        "Cơn bão nghiêm trọng",
        "Sáng",
        "Mưa và tuyết cùng nhau",
        "Mưa và mưa đá",
        "Tuyết, tuyết và mưa",
        "Đóng băng Mưa Phùn",
        "Mưa Phùn",
        "Lạnh Rain",
        "Rain",
        "Rain",
        "Tuyết",
        "Mưa và tuyết",
        "Tuyết với gió",
        "Tuyết",
        "Mưa đá",
        "Frost",
        "Bụi",
        "Sương mù",
        "Rải rác và sương mù",
        "Hút thuốc",
        "Gió",
        "Gió",
        "Lạnh",
        "Mây",
        "Đêm mưa",
        "Mưa",
        "Đêm mưa",
        "Rõ ràng ngày",
        "Đêm Clear",
        "Nắng",
        "Đêm moonlit",
        "Ngày",
        "Mưa và mưa đá với nhau",
        "Rất nóng",
        "Sáng",
        "Rain",
        "Rain",
        "Rain",
        "Tuyết",
        "Các khóa học tuyết",
        "Tuyết",
        "Rain",
        "Mưa Phùn",
        "Mưa và tuyết",
        "Sáng",
        3200 => "không khả dụng"
        ) ,
    'persian' => array(
        'گردباد',
        'طوفان گرمسیری ',
        "طوفان",
        " طوفان های شدید ",
        " رعد و برق ",
        " و برف و باران با هم",
        " باران و تگرگ ",
        " برف و باران ",
        " انجماد نم نم باران ",
        " نم نم باران ",
        " سرد باران ",
        " باران ",
        " باران ",
        "برف ",
        " باران و برف ",
        "برف همراه با باد",
        "برف ",
        " سلام ",
        " فراست ",
        " گرد و غبار ",
        " مه آلود ",
        " مه و مه ",
        " دودی ",
        " باد ",
        " باد ",
        " سرد ",
        " ابری ",
        "شب بارانی ",
        " ابری ",
        "شب ابری ",
        " روز روشن ",
        "شب پاک ",
        "سانی ",
        " شب مهتابی ",
        "روز",
        " باران و تگرگ با هم",
        " بسیار گرم",
        " رعد و برق ",
        " باران ",
        " باران ",
        " باران ",
        " برف سنگین ",
        " دوره های برف ",
        " برف سنگین ",
        " باران ",
        " نم نم باران ",
        " باران و برف ",
        " رعد و برق ",
        3200 => " در دسترس نیست "
        )
    ),
    'days' => array( // this is clucnky as hell. We get a shortcode back from Yahoo! then convert it to an int to reference terms!
        'english' => array(
            "Sun" => 12, //Sunday
            "Mon" => 13, //Monday
            "Tue" => 14, //Tuesday
            "Wed" => 15, //Wednesday
            "Thu" => 16, //Thursday
            "Fri" => 17, //Friday
            "Sat" => 18  //Saturday
        )
    ),
    'terms' => array(
        'english'=>array(
            "Wind speed",
            "Direction",
            "Today",
            "North",
            "East",
            "South",
            "West",
            "Sunrise",
            "Sunset",
            "Humidity",
            "Visibility",
            "Pressure",
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
            ),
        'persian'=>array(
            "سرعت باد",
            "جهت",
            "امروز",
            "شمال",
            "شرق",
            "جنوب",
            "غرب",
            "طلوع",
            "غروب",
            "رطوبت",
            "دید",
            "فشار",
            "یکشنبه",
            "دوشنبه",
            "سه شنبه",
            "چهارشنبه",
            "پنج شنبه",
            "جمعه",
            "شنبه"
            ),
        'arabic'=>array(
            "سرعة الرياح",
            "الاتجاه",
            "اليوم",
            "الشمال",
            "الشرق",
            "الجنوب",
            "الغربية",
            "شروق الشمس",
            "غروب الشمس",
            "الرطوبة",
            "الرؤية",
            "الضغط",
            "الأحد",
            "الاثنين",
            "الثلاثاء",
            "يوم الأربعاء",
            "الخميس",
            "الجمعة",
            "السبت"
            ),
        'bulgarian'=>array(
            "Скорост на вятъра",
            "Посока",
            "Днес",
            "Север",
            "Изток",
            "Юг",
            "Запад",
            "Изгрев",
            "Залез",
            "Влага",
            "видимост",
            "налягане",
            "Неделя",
            "Понеделник",
            "Вторник",
            "Сряда",
            "Четвъртък",
            "Петък",
            "Събота"
            ),
        'catalan'=>array(
            "Velocitat de vent",
            "Direcció",
            "Avui",
            "Nord",
            "Est",
            "Sud",
            "Oest",
            "Alba",
            "Capvespre",
            "La humitat",
            "visibilitat",
            "pressió",
            "Diumenge",
            "Dilluns",
            "Dimarts",
            "Dimecres",
            "Dijous",
            "Divendres",
            "Dissabte"
            ),
        'chinese-simplified'=>array(
            "风电速度",
            "方向",
            "今天",
            "北",
            "东",
            "南方",
            "西",
            "日出",
            "日落",
            "湿度",
            "可见性",
            "压力",
            "星期日",
            "星期一",
            "星期二",
            "星期三",
            "星期四",
            "星期五",
            "星期六"
            ),
        'chinese-traditional'=>array(
            "風電速度",
            "方向",
            "今天",
            "北",
            "東",
            "南方",
            "西",
            "日出",
            "日落",
            "濕度",
            "可見度",
            "壓力",
            "星期日",
            "星期一",
            "星期二",
            "星期三",
            "星期四",
            "星期五",
            "星期六"
            ),
        'danish'=>array(
            "Vindhastigheden",
            "Retning",
            "I dag",
            "Nord",
            "Øst",
            "Syd",
            "Vesten",
            "Sunrise",
            "Solnedgang",
            "Fugt",
            "synlighed",
            "pres",
            "Søndag",
            "Mandag",
            "Tirsdag",
            "Onsdag",
            "Torsdag",
            "Fredag",
            "Lørdag"
            ),
        'dutch'=>array(
            "Windsnelheid",
            "Richting",
            "Vandaag",
            "Noorden",
            "East",
            "Zuid",
            "West",
            "Sunrise",
            "Sunset",
            "Vochtigheid",
            "zichtbaarheid",
            "druk",
            "Zondag",
            'Maandag',
            "Dinsdag",
            "Woensdag",
            "Donderdag",
            "Vrijdag",
            "Zaterdag"
            ),
        'estonian'=>array(
            "Tuule kiirus",
            "Suund",
            "Täna",
            "Põhja",
            "Ida",
            "Lõuna",
            "Lääne",
            "Sunrise",
            "Sunset",
            "Õhuniiskus",
            "nähtavus",
            "surve",
            "Pühapäev",
            "Esmaspäev",
            "Teisipäev",
            "Kolmapäeval",
            "Neljapäev",
            "Reede",
            "Laupäev"
            ),
        'finnish'=>array(
            "Tuulennopeus",
            "Suunta",
            "Tänään",
            "North",
            "East",
            "Etelä",
            "West",
            "Sunrise",
            "Auringonlasku",
            "Kosteus",
            "näkyvyys",
            "paine",
            "Sunnuntai",
            "Monday",
            "Tiistai",
            "Keskiviikko",
            "Torstai",
            "Perjantai",
            "Lauantai"
            ),
        'german'=>array(
            "Windgeschwindigkeit",
            "Richtung",
            "Heute",
            "Norden",
            "Osten",
            "Süden",
            "West",
            "Sunrise",
            "Sunset",
            "Feuchtigkeit",
            "Sichtbarkeit",
            "Druck",
            "Sonntag",
            "Montag",
            "Dienstag",
            "Mittwoch",
            "Donnerstag",
            "Freitag",
            "Samstag"
            ),
        'french'=>array(
            "Vitesse de vent",
            "Sens",
            "Aujourd'hui",
            "Nord",
            "East",
            "Sud",
            "L'ouest",
            "Sunrise",
            "Sunset",
            "L'humidité",
            "visibilité",
            "pression",
            "Dimanche",
            "Lundi",
            "Mardi",
            "Mercredi",
            "Jeudi",
            "Vendredi",
            "Samedi"
            ),
        'greek'=>array(
            "Ταχύτητα του ανέμου",
            "Κατεύθυνση",
            "Σήμερα",
            "Βορρά",
            "Ανατολή",
            "Νότια",
            "Δύση",
            "Sunrise",
            "Sunset",
            "Υγρασία",
            "ορατότητα",
            "πίεση",
            "Κυριακή",
            "Δευτέρα",
            "Τρίτη",
            "Τετάρτη",
            "Πέμπτη",
            "Παρασκευή",
            "Σάββατο"
            ),
        'haitian-creole'=>array(
            "Van vitès",
            "Dirèksyon",
            "Jodi a",
            "Nò",
            "Est",
            "Sid",
            "West",
            "Sunrise",
            "Sunset",
            "Imidite",
            "visibilité",
            "pwesyon",
            "Dimanch",
            "Lendi",
            "Madi",
            "Mèkredi",
            "Jedi",
            "Vandredi",
            "Samdi"
            ),
        'hindi'=>array(
            "पवन गति",
            "दिशा",
            "आज",
            "उत्तरी",
            "पूर्व",
            "दक्षिण",
            "पश्चिम",
            "सूर्योदय",
            "सूर्यास्त",
            "नमी",
            "दृश्यता",
            "दबाव",
            "रविवार",
            "सोमवार",
            "मंगलवार",
            "बुधवार",
            "गुरुवार",
            "शुक्रवार",
            "शनिवार"
            ),
        'indonesian'=>array(
            "Kecepatan angin",
            "Arah",
            "Hari ini",
            "Utara",
            "Timur",
            "Selatan",
            "Barat",
            "Matahari terbit",
            "Sunset",
            "Kelembaban",
            "visibilitas",
            "tekanan",
            "Minggu",
            "Senin",
            "Selasa",
            "Rabu",
            "Kamis",
            "Jumat",
            "Sabtu"
            ),

        'italian'=>array(
            "Velocità del vento",
            "Direzione",
            "Oggi",
            "Nord",
            "Oriente",
            "Sud",
            "Ovest",
            "Sunrise",
            "Tramonto",
            "Umidità",
            "visibilità",
            "pressione",
            "Domenica",
            "Lunedì",
            "Martedì",
            "Mercoledì",
            "Giovedì",
            "Venerdì",
            "Sabato"
            ),
        'japanese'=>array(
            "風の速度",
            "方向",
            "今日",
            "北",
            "東",
            "南",
            "西"
            ),
        'korean'=>array(
            "풍속",
            "방향",
            "오늘",
            "북한",
            "동쪽",
            "남쪽",
            "서쪽",
            "선라이즈",
            "일몰",
            "습도",
            "표시 유형",
            "압력",
            "일요일",
            "월요일",
            "화요일",
            "수요일",
            "목요일",
            "금요일",
            "토요일"
            ),
        'latvian'=>array(
            "Vēja ātrums",
            "Virziens",
            "Šodien",
            "Ziemeļi",
            "Austrumi",
            "Dienvidos",
            "Rietumi",
            "Sunrise",
            "Sunset",
            "Mitrums",
            "uztveramība",
            "spiediens",
            "Sunday",
            "Pirmdiena",
            "Otrdiena",
            "Trešdiena",
            "Ceturtdiena",
            "Piektdiena",
            "Sestdiena"
            ),
        'maltese'=>array(
            "Kelajuan angin",
            "Arahan",
            "Semalam",
            "Nord",
            "Tal-Lvant",
            "Isfel",
            "Punent",
            "Sunrise",
            "Sunset",
            "Umdità",
            "viżibilità",
            "pressjoni",
            "Il-Ħadd",
            "It-tnejn",
            "Tlieta",
            "Erbgħa",
            "Ħamis",
            "Ġimgħa",
            "Sibt"
            ),
        'romanian'=>array(
            "Viteza vântului",
            "Direcţia",
            "Azi",
            "Nord",
            "Est",
            "Sud",
            "Vest",
            "Sunrise",
            "Apus de soare",
            "Umiditate",
            "vizibilitatea",
            "presiune",
            "Duminica",
            "Luni",
            "Tuesday",
            "Miercuri",
            "Joi",
            "Vineri",
            "Sambata"
            ),
        'russian'=>array(
            "Скорость ветра",
            "Направление",
            "Сегодня",
            "Север",
            "Восток",
            "Юг",
            "Запад",
            "Восход солнца",
            "Закат",
            "Влажность воздуха",
            "видимость",
            "давление",
            "Воскресенье",
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота"
            ),
        'spanish'=>array(
            "Viento",
            "Orientación",
            "Hoy",
            "Norte",
            "Oriente",
            "Sur",
            "Occidente",
            "Amanecer",
            "Sunset",
            "Humedad",
            "visibilidad",
            "presión",
            "Domingo",
            "Lunes",
            "El martes",
            "Miércoles",
            "El jueves",
            "El viernes",
            "Sábado"
            ),
        'swedish'=>array(
            "Vindens hastighet",
            "Riktning",
            "Idag",
            "North",
            "East",
            "Söder",
            "West",
            "Sunrise",
            "Sunset",
            "Fukt",
            "synlighet",
            "tryck",
            "Söndag",
            "Måndag",
            "Tisdag",
            "Onsdag",
            "Torsdag",
            "Fredag",
            "Lördag"
            ),
        'turkish'=>array(
            "Rüzgar hızı",
            "Yönü",
            "Bugün",
            "Kuzey",
            "Doğu",
            "Güney",
            "West",
            "Sunrise",
            "Sunset",
            "Nem",
            "görüş",
            "baskı",
            "Pazar",
            "Pazartesi",
            "Salı",
            "Çarşamba",
            "Perşembe",
            "Cuma",
            "Cumartesi"
            ),
        'ukrainian'=>array(
            "Вітер швидкістю",
            "Дирекція",
            "Сьогодні",
            "Північ",
            "Схід",
            "Південь",
            "Захід",
            "Схід",
            "Захід",
            "Вологості",
            "видимість",
            "тиску",
            "Неділя",
            "Понеділок",
            "Вівторок",
            "Середовища",
            "П'ятниця",
            "П'ятниця",
            "Суботи"
            ),
        'vietnamese'=>array(
            "Tốc độ gió",
            "Hướng",
            "Hôm nay",
            "Bắc",
            "Đông",
            "Nam",
            "Tây",
            "Mặt trời mọc",
            "Lặn",
            "Độ ẩm",
            "tầm nhìn",
            "áp",
            "Chủ nhật",
            "Thứ hai",
            "Thứ ba",
            "Thứ tư",
            "Thứ năm",
            "Thứ sáu",
            "Thứ bảy"
            )
        )
);
